version: '3.8'

services:
  outer_api:
    build:
      context: ../SelectFood
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - inner_api
  inner_api:
    build:
      context: ./inner_api
      dockerfile: Dockerfile.prod
    command: gunicorn rest_server.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - inner_api
volumes:
  postgres_data:
